INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME) VALUES (1, 'myTeam', 'member1');
INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME) VALUES (2, 'myTeam', 'member2');
INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME) VALUES (3, 'myTeam', 'member3');