DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_ID INTEGER      NOT NULL AUTO_INCREMENT,
    TEAM_ID   VARCHAR(100) NOT NULL,
    USERNAME  VARCHAR(100) NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);