INSERT INTO MEMBER VALUES (1, 'Elma');
INSERT INTO MEMBER VALUES (2, 'Charlie');
INSERT INTO MEMBER VALUES (3, 'Darren');
INSERT INTO MEMBER VALUES (4, 'Apple');
INSERT INTO MEMBER VALUES (5, 'Blue');
INSERT INTO MEMBER VALUES (6, 'Flower');